### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mentalityStyle** [A-KTO-Tbl/Dotcoin#1]
2024-07-23 18:42:33 | 🔴 | Ошибка инициализации! | ACCOUNT_1

**Comment by mentalityStyle** [comment]
this is my account json file (just 1 acc added)
{
    "ACCOUNT_1": "https://app.dotcoin.bot/#tgWebAppData=query_id%3DAAGFezef83AwAXXzAAF7N_zemQzR2%26user%3D%7B%22id%22%3A738196AZ23078%2C%22first_name%22%3A%22momentom%22%2C%22last_name%22%3A%22%22%2C%22username%22%3A%22biolodpn%22%2C%22language_code%22%3A%22en%22%2C%22allows_write_to_pm%22%3Atrue%7D%26auth_date%3D172Z31637541%26hash%3D5c5341a0645f72ebb8ac657b39072411ss31d811c0b9b5c0c97975df7c253900461&tgWebAppVersion=7.4&tgWebAppPlatform=android&tgWebAppThemeParams=%7B"bg_color"%3A"%2321233d3b"%2C"section_bg_color"%3A"%231d234733"%2C"secondary_bg_color"%3A"%231z51e27"%2C"text_color"%3A"%23ffffff"%2C"hint_color"%3A"%237d8b99"%2C"link_color"%3A"%235eabe1"%2C"button_color"%3A"%2350a8eb"%2C"button_text_color"%3A"%23ffffff"%2C"header_bg_color"%3A"%232425zd39"%2C"accent_text_color"%3A"%2364b5ef"%2C"section_header_text_color"%3A"%2379c4fc"%2C"subtitle_text_color"%3A"%237b8790"%2C"destructive_text_color"%3A"%23ee68z6f"%7D"
}

**Comment by A-KTO-Tbl** [comment]
The link you provided is incorrect. The link must end with "7D"
