### ISSUE TITLE
don't run

### ISSUE THREAD

**Issue by mentalityStyle** [A-KTO-Tbl/Dotcoin#2]
It was working yesterday, it is not working today
there is a problem
you can check dear?

**Comment by A-KTO-Tbl** [comment]
Недавно вышло обновление Dotcoin, скоро будет обновлён и скрипт

**Comment by mentalityStyle** [comment]
> Dotcoin has recently been updated, and the script will be updated soon.
tnx
😱you'r realy best and fast 🙂
